<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BackOffice</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" /> 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="assets/css/cocktails.css">
</head>
<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
                <a class="navbar-brand" href="index.php"><i class="fas fa-cocktail"></i></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
        
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?php include 'templates/inc/nav.phtml' ?>
                    <form action="" class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="recherche">
                        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
            <div class="header">
                <h1>Mister Cocktails</h1>
            </div>
        </div>
    </header>
    <main class="row">
        <div class="modal d-none">
            <img src="" alt="">
        </div>
        <div class="container">
            <h2>Liste des cocktails <i class="fas fa-cocktail"></i> dans la base de données</h2>
            <div class="row">
                <div class="col-12">
                    <div class="nav-item dropdown active border border-dark mb-3">
                    <a class="nav-link dropdown-toggle btn btn-outline-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Filtrer par catégorie de cocktails</a>
                            <div class="dropdown-menu bg-light" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="backOffice.php">-- Tous les cocktails -- (<?=$nbreCocktails['nbreCocktails']?>)</a>
                                <?php foreach($listeFamille AS $soustableau) { ?>
                                    <a class="dropdown-item" href="<?='?categorie=' . $soustableau['nomFamille']?>"><?=$soustableau['nomFamille']?> (<?=$soustableau['nbreParFamille'] ?>)</a>
                                    <!-- <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a> -->
                        
                                <?php } ?>
                            </div>
                        </div>
                        <div class="message d-block opacity-5">
                            <?php echo $_SESSION['msg']; $_SESSION['msg'] = ''; ?>
                        </div>
                        <div class="message2 d-block opacity-5">
                            <?php echo $msg; $msg=''; ?>
                        </div>
                        <table class="table table-striped table-bordered table-light table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th>#</th>
                                    <th>Nom</th>
                                    <th>Photo</th>
                                    <th>Famille</th>
                                    <th>Modifier</th>
                                    <th>Supprimer</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($listeCocktailsBO AS $soustableau) { ?>
                                    <tr>
                                        <td class="align-middle"><?=$soustableau['id']?></td>
                                        <td class="align-middle"><?=$soustableau['nom']?></td>
                                        <td><a href="assets/images/cocktails/<?=$soustableau['urlPhoto']?>"><img src="assets/images/cocktails/<?=$soustableau['urlPhoto']?>" alt="<?=$soustableau['urlPhoto']?>" style="width:150px"></a></td>
                                        <td class="align-middle"><?=$soustableau['nomFamille']?></td>
                                        <td class="align-middle"><a href="editionCocktail.php?action=modifier&id=<?=$soustableau['id']?>"><i class="fas fa-pencil-alt"></i></a></td>
                                        <td class="align-middle"><a href="?action=supprimer&id=<?=$soustableau['id']?>" class="supprimer"><i class="fas fa-times-circle"></i></a></td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                </div> 
            </div>
        </div> 
    </main>
    <script src="assets/js/backOffice.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>