<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Détail cocktail</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" /> 
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 
        <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet"> 
        <link rel="stylesheet" href="assets/css/cocktails.css">
    </head>
    <body>
        <header>
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
                    <a class="navbar-brand" href="index.php"><i class="fas fa-cocktail"></i></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
            
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <?php include 'templates/inc/nav.phtml' ?>
                    </div>
            </nav>
            <div class="header">
                <h1>Mister Cocktails</h1>
            </div>
        </div>
        </header>
        <main> 
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2>Détails Cocktail</h2>
                        <div class="media bg-light row">
                            <div class="media-body pb-4 pt-4 pl-3 pr-3 col-sm-12 col-md-5">
                                <h5 class="mt-0 mb-5"><?=$detailsCocktail['nom']?></h5>
                                <p><?=$detailsCocktail['description']?><p>
                                <hr>
                                <p>Date de création : <?=$detailsCocktail['anneeConception']?></p>
                                <hr>
                                <p>Prix Moyen : <?=$detailsCocktail['prixMoyen']?>€</p>
                                <hr>
                                <p>Famille : <?=$detailsCocktail['nomFamille']?></p>  
                            </div>
                            <div class="col-sm-12 col-md-7 pr-0 pl-0">
                                <img src="assets/images/cocktails/<?=$detailsCocktail['urlPhoto']?>" alt="<?=$detailsCocktail['urlPhoto']?>" style="width:100%;">
                            </div>
                        </div>
                        <div id="recette" class="media bg-dark text-light pl-3 pr-3 pb-5 d-flex flex-column align-items-center opacity-4">
                            <h4 class="pt-4 mb-5">Ingrédients</h4>
                            <?php 
                                echo '<ul class="list-group">';
                                foreach($listeIngredients AS $soustableau) {
                                   echo '<li class="bg-dark text-light list-group-item border-0">' . $soustableau['nomIngredient'] . '</li>';


                                }
                                // <li class="bg-dark text-light list-group-item">2cl de jus de citons verts</li>
                                // <li class="bg-dark text-light list-group-item">1cl de sirop de sucre de canne</li>
                                // <li class="bg-dark text-light list-group-item">ingredient4</li>
                                // <li class="bg-dark text-light list-group-item">ingredient5</li>
                                // <li class="bg-dark text-light list-group-item">ingredient6</li>
                            echo '</ul>'
                            ?>
                        </div>
                        <h3>Autres cocktails de la même catégorie</h3>
                        <div class="cocktailsFamille">
                            <div id="prev" class="d-none"></div>
                            <div id="next" class="d-none"><i class="fas fa-chevron-circle-right"></i></div>
                            <div class="reglette d-flex flex-nowrap">
                                <?php foreach($listeCocktailsFam as $sousTableau) { if($sousTableau['nom'] != $detailsCocktail['nom']) { ?>
                                <div class="card2 bg-light mr-2 mb-2 h-100">
                                    <a href="detailsCocktail.php?id=<?=$sousTableau['id']?>"><img src="assets/images/cocktails/<?=$sousTableau['urlPhoto']?>" class="card-img-top" alt="<?=$sousTableau['urlPhoto']?>"></a>
                                    <div class="card-body bg-light">
                                        <a href="detailsCocktail.php?id=<?=$sousTableau['id']?>"><h5 class="card-title"><?=$sousTableau['nom'] ?></h5></a>
                                    </div>
                                </div>
                                <?php } } ?>
                            </div>
                        </div>
                        <!-- <div class=row>
                            <div class="col-5">
                                <h2><?=$detailsCocktail['nom']?></h2>
                                <p><?=$detailsCocktail['description']?></p>
                            </div>
                            <div class="col-7">
                                <img src="assets/images/cocktails/<?=$detailsCocktail['urlPhoto']?>" alt="<?=$detailsCocktail['urlPhoto']?>" style="width:600px">
                            </div>
                        </div> -->
                    </div>
                </div>
            </div>



        
        </main>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <script src="assets/js/detaillsCocktail.js"></script>
    </body>
</html>