<ul class="navbar-nav mr-auto">
                        <!-- <li class="nav-item active">
                            <a class="btn btn-outline-secondary mr-2" href="index.php">Home<span class="sr-only">(current)</span></a>
                        </li> -->
                        <li class="">
                            <a class="btn btn-outline-warning mr-2" href="ajoutCocktail.php">Ajouter un coktail</a>
                        </li>
                        <li class="">
                            <a class="btn btn-outline-danger" href="backOffice.php">Back Office</a>
                        </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li> -->
                    <!-- <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li> -->
                    </ul>